### ISSUE TITLE
html

### ISSUE THREAD

**Issue by haniali1234** [geekwise-kao-thao/plated#1]
- footer needs to be responsive 
- search bar on the image

**Comment by procommand** [comment]
```
width:32%;
height:55px;
```

////New
    width:32%;
    height:10%;
change every instance of static definition of height and width to percentage, so the browser can calculate it, rather then just go straight to a defined height.

I would recommend using twitter bootstrap, to have a more fluid and dynamic control of a website being responsive. and also it more controlled and developed, but your method is ok too, if your going to use percentages as value for measuments of each element. and by the way, if you want the whole page to be responsive from the perspective of every element, then you must define class id in the css file for every element with a percentage for each elements measurement respective of the browser screen.

**Comment by geekwise-kao-thao** [comment]
sorry it took a while to respond back, but thank you procommand.

your little advice made a huge difference as i added media query throughout this project to make it responsive.

i appreciate you reviewing and giving me generous suggestions.
